# Generated by Django 3.1.7 on 2021-03-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='from_who',
            field=models.CharField(choices=[('FromTheOwner', 'Sahibinden'), ('FromRealEstateAgent', 'Emlakçıdan')], default='FromTheOwner', max_length=30),
        ),
        migrations.AddField(
            model_name='home',
            name='furnished',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], default='False', max_length=30),
        ),
        migrations.AddField(
            model_name='home',
            name='number_of_rooms',
            field=models.CharField(choices=[('Default', 'Belirtilmemiş'), ('1', '1+1'), ('2', '2+1'), ('3', '3+1'), ('4', '4+1')], default='Default', max_length=30),
        ),
        migrations.AddField(
            model_name='home',
            name='swap',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], default='False', max_length=30),
        ),
        migrations.AddField(
            model_name='home',
            name='using_status',
            field=models.CharField(choices=[('Idle', 'Boşta'), ('OnRent', 'Kirada')], default='Idle', max_length=30),
        ),
        migrations.AlterField(
            model_name='home',
            name='building_age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='home',
            name='dues',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='home',
            name='number_of_floors',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='home',
            name='square_meters',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
