# Generated by Django 3.1.7 on 2021-04-06 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210407_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformmessage',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactformmessage',
            name='phone',
        ),
    ]
