# Generated by Django 3.2 on 2021-06-15 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated_at',
            new_name='update_at',
        ),
    ]
